language: android
android:
  components:
  - android-4
install:
- android list sdk
- android list targets
- android update project --target android-4 -p .
- echo -e "key.store=$TRAVIS_BUILD_DIR/my-release-key.keystore\nkey.alias=alias_name\nkey.store.password=$KEYSTORE_PASS\nkey.alias.password=$KEYSTORE_PASS" >> build.properties
- echo -e "key.store=$TRAVIS_BUILD_DIR/my-release-key.keystore\nkey.alias=alias_name\nkey.store.password=$KEYSTORE_PASS\nkey.alias.password=$KEYSTORE_PASS" >> local.properties
- echo -e "key.store=$TRAVIS_BUILD_DIR/my-release-key.keystore\nkey.alias=alias_name\nkey.store.password=$KEYSTORE_PASS\nkey.alias.password=$KEYSTORE_PASS" >> ant.properties
script:
- ant release
before_deploy:
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - git tag -f v$(echo -e 'setrootns\nxpath string(/manifest/@android:versionName)' | xmllint --shell AndroidManifest.xml | head -n1 | cut -d ':' -f 2 | tr -d ' ')-$TRAVIS_BRANCH-deploy
  - git push origin -f v$(echo -e 'setrootns\nxpath string(/manifest/@android:versionName)' | xmllint --shell AndroidManifest.xml | head -n1 | cut -d ':' -f 2 | tr -d ' ')-$TRAVIS_BRANCH-deploy
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: 
  - bin/*.apk
  file_glob: true
  overwrite: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
    - /^.*-deploy$/
    - /^untagged-.*$/
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_066edb11b432_key -iv $encrypted_066edb11b432_iv -in my-release-key.keystore.enc -out my-release-key.keystore -d
