language: android
install:
- android list sdk
- android list targets
- android update project --target android-4 -p .
branches:
  except:
    - /^deploy-.*$/
    - /^untagged-.*$/
notifications:
  email: false
