language: android
android:
  components:
  - build-tools-21.1.2
before_script:
- cd src/com/googlecode/droidwall
branches:
  except:
    - /^deploy-.*$/
    - /^untagged-.*$/
notifications:
  email: false
